### ISSUE TITLE
Add extension method for accessing the context mor easily

### ISSUE THREAD

**Issue by fabiancrx** [localizely/flutter-intl-plugin-sample-app#3]
Hi, currently the way to access the translations is 
```
S.of(context).loginUsername
```
while this has nothing bad with it but I think we could leverage dart extension methods to make more clear the intent when accessing a translation .A small proposal would be to add  this extension before the generated  class `l10n.dart`:
```
extension L10nHelper on BuildContext{
 S get translate=>Localizations.of<S>(this, S);
}
```
Now the translations are accessible as:
```
context.translate.loginUsername
```
or whichever name the user defines like
`context.S.loginUsername`
if the class is not named S, of course
Hope to see what you think about it!

**Comment by aleksakrstic** [comment]
Hi @fabiancrx 
Thanks for the suggestion.
Not sure that will help developers to easier type localized strings in Dart code. We will potentially add access to strings via `S.context.loginUsername` in case there is no direct access to `context`.

The thing is we want this plugin to guide a developer to not think about localization and still do it in the official way.. if we introduce additional ways how to do it, without noticeable benefits, it would confuse developers.
