### ISSUE TITLE
S.of(context).localeName not getting updated.

### ISSUE THREAD

**Issue by raminvakili8** [localizely/flutter-intl-plugin-sample-app#5]
After changing app locale using `S.load(Locale('de', 'DE'));`, the `S.of(context).localeName` still shows `en`.

Even after `setState` and when rebuilding is done. It's not updated. 

Update: Also using `Localization.localOf(context).languageCode` returns `en`.

**Comment by aleksakrstic** [comment]
Hi @raminvakili-fs 
If you want to get currently selected locale, you should do it with `Intl.getCurrentLocale()`.
You can find this and other usage info in [VS Code extension](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl) and [Android Studio plugin](https://plugins.jetbrains.com/plugin/13666-flutter-intl) docs.
